### ISSUE TITLE
Renomear attributo da tabela "offers"

### ISSUE THREAD

**Issue by vitorp** [vitorp/matricula-web-api#12]
Na criação da tabela e model "offers" ocorreu um typo e o campo que se chama "credits_pratical" deve ser renomeado para "credits_practical" ( Estou aceitando sugestões de nomes melhores tambem).

**Comment by vitorp** [comment]
Oi!
Acredito que renomear seja melhor já que não causa nenhuma inconsistência que obrigue um Drop. E em breve eu quero ver se tem como dar um Squash das migrations de qualquer jeito.

**Comment by rodriggochaves** [comment]
A ideia desse atributo é representar quantos créditos você precisa dedicar na prática para a matéria?

**Comment by vitorp** [comment]
Toda matéria tem 4 tipos de créditos como [nessa](url) por exemplo tem 004-002-000-006 que correspondem a (Teor-Prat-Ext-Est) Teóricos, práticos, extensão e estudos. Os práticos aqui se referem a atividades mais experimentais como laboratórios. Esse campo representa esse tipo de crédito que uma matéria pode ter.

**Comment by rodriggochaves** [comment]
Entendi! O que acha de `credits_of_practice` invés `credits_practical`?

**Comment by vitorp** [comment]
Boa. É melhor mesmo. Só teria que ajustar os outros creditos pra ficar credits_of_xxxx tambem.
