### ISSUE TITLE
Criar relacionamentos para o model Campus

### ISSUE THREAD

**Issue by vitorp** [vitorp/matricula-web-api#13]
O model campus existe atualmente no sistema, mas não possui nenhum relacionamento. A adição de um relacionamento com departamentos será necessária. 
**Bonus**: Implementar metodo em Course que retorna o campus daquele curso
**Ps**: Não se esqueça dos testes

**Comment by rodriggochaves** [comment]
O relacionamento entre `Campus` e `Department` é um `Campus` tem vários `Department` e um `Department` tem um `Campus`??

**Comment by vitorp** [comment]
Isso mesmo!

**Comment by vitorp** [comment]
Vamos deixar opcional por enquanto pra não atrapalhar muito a criação no scraping caso seja feito um de cada vez.
