### ISSUE TITLE
Adicionar campos de ementa ao curso

### ISSUE THREAD

**Issue by vitorp** [vitorp/matricula-web-api#14]
São no total 3 campos do tipo texto: Ementa, Bibliografia e programa. Tradução para um bom nome em inglês faz parte da tarefa kkk.

**Comment by rodriggochaves** [comment]
Vou pegar essa issue, okay?

**Comment by vitorp** [comment]
Esses campos  vão representar os correspondentes nessa [página](https://matriculaweb.unb.br/graduacao/disciplina.aspx?cod=116882)
