### ISSUE TITLE
Desenvolvimento sem docker

### ISSUE THREAD

**Issue by vitorp** [vitorp/matricula-web-api#3]
Configurar projeto para desenvolvimento com ou sem docker e adicionar documentação no CONTRIBUTTING.md . Acredito que o unico problema é o host do banco de dados. Adicionar uma variavel de ambiente pra isso deve resolver sem a pessoa precisar configurar nada quando for rodar local.

**Comment by renanreboredo** [comment]
Não entendi o que você quis dizer com docker-compose para cmd. Pode explicar melhor?

**Comment by vitorp** [comment]
Issa parte é na verdade pra melhorar o docker e o docker compose do projeto. Vou criar outra issue pra isso e explicar melhor lá.
